name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker containers
        run: docker compose build

      - name: Ensure the script has execution permission
        run: chmod +x ./coding_style_check.sh ./testing.sh

      - name: Run coding style check
        run: docker compose run --rm memonest ./coding_style_check.sh

      - name: Run tests
        run: docker compose run --rm memonest ./testing.sh

  documentation:
    runs-on: ubuntu-latest
    needs: ci

    permissions:
      contents: read
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --requirement requirements.txt

      - name: Build documentation
        run: pdoc3 --html --skip-errors --output-dir docs src

      - name: Upload documentation as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/src

      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
