name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker containers
        run: docker compose build

      - name: Run coding style check
        run: docker compose run --rm memonest ./coding_style_check.sh

      - name: Run tests
        run: docker compose run --rm memonest ./testing.sh
